name: Publish to Gitea SyPI Registry and PyPI

on:
  push

defaults:
  run:
    shell: powershell

jobs:
  publish:
    name: Publish
    runs-on: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.BUILDMASTER_PAT }} 
      - name: Set up Python environment
        uses: actions/setup-python@v5
        id: cp311
        with:
          python-version: "3.11"
          update-environment: false
      - name: Install dependencies
        run: |
          ${{ steps.cp311.outputs.python-path }} -m ensurepip
          ${{ steps.cp311.outputs.python-path }} -m pip install --upgrade pip wheel build twine --no-warn-script-location
          # ${{ steps.cp311.outputs.python-path }} -m pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu --no-warn-script-location
      - name: Publish to Gitea SyPI Registry
        run: |
          ${{ steps.cp311.outputs.python-path }} -m build
          ${{ steps.cp311.outputs.python-path }} -m twine upload dist/* --repository-url https://jenkins:3000/api/packages/SYNENTEC/pypi -u BuildMaster -p ${{ secrets.BUILDMASTER_PAT }} --cert "\\SYNENTEC-SV01\works$\004 -- Software Development\Tools\Build\Gitea.pem
"
      - name: Publish to PyPI
        run: |
          ${{ steps.cp311.outputs.python-path }} -m build
          ${{ steps.cp311.outputs.python-path }} -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}